// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT dials

lv_obj_t * ui_dials_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dials;
    cui_dials = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_dials);
    lv_obj_set_width(cui_dials, lv_pct(100));
    lv_obj_set_height(cui_dials, lv_pct(100));
    lv_obj_set_align(cui_dials, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_dials, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_pressureText;
    cui_pressureText = lv_label_create(cui_dials);
    lv_obj_set_width(cui_pressureText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_pressureText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_pressureText, -25);
    lv_obj_set_y(cui_pressureText, 5);
    lv_obj_set_align(cui_pressureText, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(cui_pressureText, "9 bar");
    ui_object_set_themeable_style_property(cui_pressureText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(cui_pressureText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(cui_pressureText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_pressureText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_pressureText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_pressureText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_pressureText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_tempText;
    cui_tempText = lv_label_create(cui_dials);
    lv_obj_set_width(cui_tempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_tempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_tempText, 25);
    lv_obj_set_y(cui_tempText, 5);
    lv_label_set_text(cui_tempText, "92°C");
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(cui_tempText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_pad_left(cui_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_tempIcon;
    cui_tempIcon = lv_img_create(cui_dials);
    lv_img_set_src(cui_tempIcon, &ui_img_1951499226);
    lv_obj_set_width(cui_tempIcon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(cui_tempIcon, LV_SIZE_CONTENT);    /// 40
    lv_obj_add_flag(cui_tempIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_tempIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_tempIcon, 150);
    lv_obj_set_style_img_recolor(cui_tempIcon, lv_color_hex(0xF62C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_tempIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image6;
    cui_Image6 = lv_img_create(cui_dials);
    lv_img_set_src(cui_Image6, &ui_img_1220767159);
    lv_obj_set_width(cui_Image6, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(cui_Image6, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(cui_Image6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_Image6, 150);
    lv_obj_set_style_img_recolor(cui_Image6, lv_color_hex(0x2CA4F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_Image6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIALS_NUM);
    children[UI_COMP_DIALS_DIALS] = cui_dials;
    children[UI_COMP_DIALS_PRESSURETEXT] = cui_pressureText;
    children[UI_COMP_DIALS_TEMPTEXT] = cui_tempText;
    children[UI_COMP_DIALS_TEMPICON] = cui_tempIcon;
    children[UI_COMP_DIALS_IMAGE6] = cui_Image6;
    lv_obj_add_event_cb(cui_dials, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dials, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dials_create_hook(cui_dials);
    return cui_dials;
}

